<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Project="..\props\CodeAnalysis.props"/>

  <ItemGroup>
    <EmbeddedResource Include="..\.editorconfig" Visible="false"/>
    <EmbeddedResource Include="..\PromptLibrary\CommitMessage.md" Visible="false"/>
    <ProjectReference Include="..\TedToolkit.CodeAnalysis\TedToolkit.CodeAnalysis.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
    <PackageReference Include="GeminiDotnet.Extensions.AI"/>
    <PackageReference Include="ModularPipelines.DotNet"/>
    <PackageReference Include="ModularPipelines.Git"/>
    <PackageReference Include="ModularPipelines.GitHub"/>
    <PackageReference Include="TextCopy" />
  </ItemGroup>

</Project>
